// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _median_filter_HH_
#define _median_filter_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct median_filter : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > window_address0;
    sc_out< sc_logic > window_ce0;
    sc_out< sc_logic > window_we0;
    sc_out< sc_lv<32> > window_d0;
    sc_in< sc_lv<32> > window_q0;
    sc_out< sc_lv<32> > median;
    sc_out< sc_logic > median_ap_vld;


    // Module declarations
    median_filter(sc_module_name name);
    SC_HAS_PROCESS(median_filter);

    ~median_filter();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<5> > i_i_cast_fu_105_p1;
    sc_signal< sc_lv<5> > i_i_cast_reg_165;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > exitcond_i_fu_109_p2;
    sc_signal< sc_lv<32> > key_reg_183;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > j_0_in_i_cast_fu_120_p1;
    sc_signal< sc_lv<32> > j_0_in_i_cast_reg_189;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<5> > j_fu_124_p2;
    sc_signal< sc_lv<5> > j_reg_194;
    sc_signal< sc_lv<1> > tmp_1_i_fu_134_p2;
    sc_signal< sc_lv<1> > tmp_1_i_reg_199;
    sc_signal< sc_lv<4> > i_fu_159_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > tmp_3_i_fu_145_p2;
    sc_signal< sc_lv<4> > i_i_reg_83;
    sc_signal< sc_lv<5> > j_0_in_i_reg_95;
    sc_signal< sc_lv<64> > tmp_i_fu_115_p1;
    sc_signal< sc_lv<64> > tmp_2_i_fu_140_p1;
    sc_signal< sc_lv<64> > tmp_6_i_fu_150_p1;
    sc_signal< sc_lv<64> > tmp_4_i_fu_154_p1;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > j_cast_fu_130_p1;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<64> ap_const_lv64_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<4> ap_const_lv4_9;
    static const sc_lv<5> ap_const_lv5_1F;
    static const sc_lv<5> ap_const_lv5_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond_i_fu_109_p2();
    void thread_i_fu_159_p2();
    void thread_i_i_cast_fu_105_p1();
    void thread_j_0_in_i_cast_fu_120_p1();
    void thread_j_cast_fu_130_p1();
    void thread_j_fu_124_p2();
    void thread_median();
    void thread_median_ap_vld();
    void thread_tmp_1_i_fu_134_p2();
    void thread_tmp_2_i_fu_140_p1();
    void thread_tmp_3_i_fu_145_p2();
    void thread_tmp_4_i_fu_154_p1();
    void thread_tmp_6_i_fu_150_p1();
    void thread_tmp_i_fu_115_p1();
    void thread_window_address0();
    void thread_window_ce0();
    void thread_window_d0();
    void thread_window_we0();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
